### ISSUE TITLE
期望AES加解密可以支持调整 模式/填充/偏移量/输出编码(base64|Hex)/输入编码(utf-8|gbk|...)等

### ISSUE THREAD

**Issue by MrLSC** [baiy/Ctool#107]
期望AES加解密可以支持调整 模式/填充/偏移量/输出编码(base64|Hex)/输入编码(utf-8|gbk|...)等

**Comment by changhr2013** [comment]
我大概看了一下 crypto-js 的文档，实现起来倒是不太复杂，但是想要与其他语言做互通的话，需要更改现有的一些数据形式，典型的，目前的『密码/密钥』输入框，需要明确更改为『密钥』输入框，而且需要明确指定密钥格式（base64 | hex）。

密码形式建议不再做支持，crypto-js 如果检测到输入是 string 的时候，会做密钥衍生和随机 iv 生成，对于这种工具性质的应用来说，一般没有什么用处，还会对使用方造成困扰。

国密算法中，目前引入的 sm-crypto 库只对 sm4 的 ECB | CBC 做了支持，想要扩展其他模式的话，工作量有点大，可以暂时不做支持。

我的主技术栈毕竟是 java/golang，对 js 不太熟悉，可以先照猫画虎把算法层实现了，UI 上后期 @baiy 再做调整。

大概这几天，我按照这个思路先实现一版看看。

**Comment by changhr2013** [comment]
https://i.goto327.top/CryptTools/SymmCrypt.aspx

这个网站实现的算法比较标准，可以参考一下。😁

**Comment by baiy** [comment]
新版已支持
