### ISSUE TITLE
能否考虑下添加json <-> 各个语言struct互转

### ISSUE THREAD

**Issue by zhangweiii** [baiy/Ctool#116]
目前这个插件是功能最全，用着最好的
如果再加上json和结构体互转，就完美了

**Comment by baiy** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2341581/155947049-199427cd-271b-4e1e-bb83-7018670a7bac.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2341581/155947087-b07c24dd-393e-48de-a825-9b35af96121c.png">
