### ISSUE TITLE
时间戳展示最后一个单位应该是ms吗

### ISSUE THREAD

**Issue by hecan1020** [baiy/Ctool#117]
![image](https://user-images.githubusercontent.com/42570304/157366678-6cd65617-dff4-4568-be2a-6547e3302f50.png)

**Comment by baiy** [comment]
这里应该是毫秒 下一版本来修复

**Comment by hecan1020** [comment]
> 这里应该是毫秒 下一版本来修复

嗯嗯，谢谢大佬的工具
