### ISSUE TITLE
希望添加yml和properties互相转换的功能

### ISSUE THREAD

**Issue by tanggangcm** [baiy/Ctool#119]
希望添加yml和properties互相转换的功能

**Comment by baiy** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/2341581/157614324-6367943c-be8b-45be-ac0c-91c737bfbdfc.png">

**Comment by tanggangcm** [comment]
大哥，我错了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月10日 15:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [baiy/Ctool] 希望添加yml和properties互相转换的功能 (Issue #119) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rookiezq** [comment]
![image](https://user-images.githubusercontent.com/43901891/164722106-ab7078f5-4c56-4543-9b36-17c122327d32.png)
能不能转换成这种格式啊？
