### ISSUE TITLE
开发者视角：生成开发代码

### ISSUE THREAD

**Issue by songxing10000** [baiy/Ctool#13]
场景1:
中文翻译成英文的属性名、方法名、控件名等，涉及语言 objc、swift、weex
比如
姓名、年龄     在谷歌翻译成  name、age
这里我们则可能需要生成对应代码：
oc
```objc
/// 姓名
@property(copy, nonatomic) NSString *m_name;
/// 年龄
@property(copy, nonatomic) NSString *m_age;
```
swift
```swift
// 生成属性
/// 姓名
var m_name: String?
/// 年龄
var m_age: String?
// 生成控件连线 label button 
/// 姓名
@IBOutlet weak var m_nameLabel: UILabel!
/// 姓名
@IBOutlet weak var m_nameBtn: UIButton!
```
weex下的jsdoc
```js
/* 
* 姓名
 * @type {string}
*/
m_name: ''
```
场景2:
开发中经常接入接口到代码里，url 入参 返回值，生成模型等
这里则需要拿到当前网页的url，解析域名及路径、请求方式等生成注释
如：
```swift
     // MARK: 获取工作日志详情
    /// 获取工作日志详情 http://ult-ga.....ge/preview/928
    let getDetailWorkLog = XSNetworkRequestMethod(method: .get, path: "entprise/workLog/basic/detail", replace: "")
```
如，抓取接口文档 里的返回的模型生成swift下或者 java下的bean
```swift
class KYWorkDiaryDetailCommentModel: Mappable {
    
    
    /// 员工用户名
    var name: String?
    var userId: String?
    var avatar: String?
    /// 评论时间
    var createTime: String?
    /// 评论id
    var id: String?
    /// 评论内容
    var content: String?
    var employeeId: String?
    required init?(map: Map) { }
    init() {
        
    }
    func mapping(map: Map) {
        
        name <- map["name"]
        userId <- map["userId"]
        avatar <- map["avatar"]
        createTime <- map["createTime"]
        id <- map["id"]
        content <- map["content"]
        employeeId <- map["employeeId"]
    }
    
}
```
等 等

如果没有这种谷歌插件工具，我们也能开发，只不过是一个一个的复制 ，当然有些开发都连字段注释也懒得复制到代码中，就会导致不清楚某个字段时会去看网页文档，连这个接口文档的url也没放代码里时，就还得问其他开发人员，太低效率了

**Comment by songxing10000** [comment]
我现在实现的样式太丑，对插件、前端开发完全不懂...
![image](https://user-images.githubusercontent.com/10040131/63864499-86086600-c9e2-11e9-8b6b-c5d4a27f4e76.png)
感觉你这工具不错，要是能加上代码高亮，就太帅了

**Comment by baiy** [comment]
你这个需求定制化程度太高了 不太适合放在通用的开发工具集中
而且代码生成涉及到的功能和语言较多, 最好是单独开发一个工具

**Comment by songxing10000** [comment]
是啊，我也知道，这个插件属于高度自定义，可能只适合某些场景下使用，我还写了个类似的直接从后台的接口文档中，生成iOS代码出参入参返回model的功能。
找到个这种的模板
![image](https://user-images.githubusercontent.com/10040131/63993678-4b0e4b80-cb24-11e9-985b-48b66c52345a.png)
不过，感觉你的插件的风格挺漂亮的，我能快速使用你这种模板吗，我看直接下载你源码，没法加载进谷歌啊为啥

**Comment by baiy** [comment]
当前版本的插件是使用[vue](https://vuejs.org/)+[iviewui](https://www.iviewui.com/)开发  需要webpack打包编译  对前端工作流不熟悉的同学可能确实比较困难

[老版本(0.0.3)插件](https://github.com/baiy/Ctool/tree/0.0.3) 是使用[layui](https://www.layui.com/)开发的UI,界面类似,没有使用打包工具, 对于不熟悉前端工作流的同学比较友好,可以参考一下

**Comment by songxing10000** [comment]
不错啊
