### ISSUE TITLE
能否增加一个modbus crc16 校验码计算

### ISSUE THREAD

**Issue by qjiang888** [baiy/Ctool#139]
base64 加密能否增加 hex类型的数据加密！
类似这个网站https://the-x.cn/base64

**Comment by baiy** [comment]
hex/base64 #129

**Comment by baiy** [comment]
modbus crc16 这个不太了解 希望可以提供具体算法或者代码

**Comment by qjiang888** [comment]
add8的算法：
/********************************
&nbsp;*&nbsp;
&nbsp;* Notes: Checksum 8 byte
&nbsp;*&nbsp;
&nbsp;* Start 0 to the end
&nbsp;*&nbsp;
&nbsp;* Example：&nbsp; HEX
&nbsp;*&nbsp;
&nbsp;* In&nbsp; -&gt; 12 34&nbsp;
&nbsp;* Out -&gt; 12 34 46&nbsp;
&nbsp;*&nbsp;
&nbsp;*******************************/


(
&nbsp; &nbsp; function main() {
&nbsp; &nbsp; &nbsp; &nbsp; source = this.SourceDataBuffer; //Source data buffer;


&nbsp; &nbsp; &nbsp; &nbsp; var buf = new ArrayBuffer(source.length + 1)
&nbsp; &nbsp; &nbsp; &nbsp; var newBuffer = new Uint8Array(buf);


&nbsp; &nbsp; &nbsp; &nbsp; newBuffer[newBuffer.length - 1] = 0;
&nbsp; &nbsp; &nbsp; &nbsp; for (var i = 0; i < source.length; i++) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newBuffer[i] = source[i];
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newBuffer[newBuffer.length - 1] += source[i];
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; return newBuffer;
&nbsp; &nbsp; }
)()


crc16-modbus的算法：




/********************************
&nbsp;*&nbsp;
&nbsp;* Notes: CRC16-Modbus
&nbsp;*&nbsp;
&nbsp;* x16+x15+x2+1&nbsp; &nbsp; 0x8005 -&gt; 0xA001&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp;*&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0x1021 -&gt; 0x8408
&nbsp;*&nbsp;
&nbsp;* Example： HEX
&nbsp;*&nbsp;
&nbsp;* In -&gt; 12 34&nbsp;
&nbsp;* Out-&gt; 12 34 0C C7
&nbsp;*&nbsp;
&nbsp;*******************************/


(
&nbsp; &nbsp; function main() {
&nbsp; &nbsp; &nbsp; &nbsp; source = this.SourceDataBuffer; //Source data buffer;
&nbsp; &nbsp; &nbsp; &nbsp; var buf = new ArrayBuffer(source.length + 2); //Create a new array
&nbsp; &nbsp; &nbsp; &nbsp; var newBuffer = new Uint8Array(buf);


&nbsp; &nbsp; &nbsp; &nbsp; //Adding check
&nbsp; &nbsp; &nbsp; &nbsp; for (var i = 0; i < source.length; i++)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newBuffer[i] = source[i];


&nbsp; &nbsp; &nbsp; &nbsp; var crc = 0xFFFF;
&nbsp; &nbsp; &nbsp; &nbsp; for (var i = 0; i < source.length; i++) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; crc ^= (source[i] &amp; 0x00FF);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for (var j = 0; j < 8; j++) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (crc &amp; 0x01) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; crc &gt;&gt;= 1;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; crc ^= 0xA001;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; else
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; crc &gt;&gt;= 1;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; newBuffer[source.length] = crc;
&nbsp; &nbsp; &nbsp; &nbsp; newBuffer[source.length + 1] = crc &gt;&gt; 8;
&nbsp; &nbsp; &nbsp; &nbsp; return newBuffer;
&nbsp; &nbsp; }
)()










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baiy/Ctool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baiy/Ctool] 能否增加一个modbus crc16 校验码计算 (Issue #139)





 
modbus crc16 这个不太了解 希望可以提供具体算法或者代码
