### ISSUE TITLE
手动安装插件失败

### ISSUE THREAD

**Issue by xuegeliu** [baiy/Ctool#14]
![image](https://user-images.githubusercontent.com/34851453/63910892-feab0900-ca5a-11e9-958d-81a713f64a1f.png)

**Comment by xuegeliu** [comment]
在市场安装后，一点击为啥直接滚动到最底部了，或者切换上方的tab也会直接滚动到最底部
![image](https://user-images.githubusercontent.com/34851453/63911024-809b3200-ca5b-11e9-8275-8206e7bff597.png)

**Comment by baiy** [comment]
关于无法安装的问题:
Chrome 67以后的， 
谷歌开始限制用户从第三方网站下载安装插件。 
大量的离线安装方法逐渐不被支持。 
[可以点击参考这篇文章](https://leanote.zzzmh.cn/blog/post/admin/Chrome-73-%E5%AE%89%E8%A3%85crx%E6%89%A9%E5%B1%95%E6%8F%92%E4%BB%B6%E6%96%B9%E6%B3%95%E6%B1%87%E6%80%BB%EF%BC%8C%E8%A7%A3%E5%86%B3CRX-HEADER-INVALID-2)

建议有条件的还是商店安装

**Comment by baiy** [comment]
第二个问题
实际上你这个页面是不会出现滚动条, 猜测原因可能是
1.  使用了高分屏, 在windows下确实容易出现界面异常
2. 页面中出现了报错,造成有异常内容输出, 干扰了页面正常显示, 可以在页面上右击`检查`打开开发者工具查一下页面布局代码

**Comment by xuegeliu** [comment]
已从市场安装，用的mac pro 15的非retina屏，调整了网页的100%也是会自动 滚动 到底部。新打开 个空白标签页，点你的插件也会自动 滚动到最底部。

**Comment by baiy** [comment]
页面大小是固定的 你可以打开开发者工具查看一下页面大小变化的原因
![image](https://user-images.githubusercontent.com/2341581/63997963-93346a80-cb32-11e9-9abd-3b13f7d387d2.png)
