### ISSUE TITLE
文本替换时，无法替换换行符号

### ISSUE THREAD

**Issue by XYZliang** [baiy/Ctool#143]
如题，比如一下一个例子
`1`
`2`
`3`
`4`
想要替换成
`1、2、3、4`
在替换中查找框键入一个换行，右边替换框输入、是无法替换的，只能通过去除换行符功能后，奖空格替换为、

**Comment by baiy** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/2341581/179949706-5fde39e0-54f4-44a3-a202-56bacefa8b6d.png">
