### ISSUE TITLE
url解码不支持中文

### ISSUE THREAD

**Issue by Asura88** [baiy/Ctool#148]
%E5%AE%89%E5%BE%BD%E4%B8%AD%E6%8E%98%E5%BB%BA%E8%AE%BE%E5%B7%A5%E7%A8%8B%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%EF%BC%88%E5%8F%8C%E9%B8%AD%E5%B1%B1%E5%B8%82%E5%BB%BA%E9%BE%99%E7%9F%BF%E4%B8%9A%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%E5%8D%97%E5%8C%BA%E9%A1%B9%E7%9B%AE%E9%83%A8%EF%BC%89%E6%9C%AA%E8%90%BD%E5%AE%9E%E5%AE%89%E5%85%A8%E7%94%9F%E4%BA%A7%E8%B4%A3%E4%BB%BB%E5%88%B6%E7%AD%89%E6%A1%88%E3%80%82%E4%B8%BB%E8%A6%81%E8%AF%81%E6%8D%AE%E4%B8%80%EF%BC%9A%E3%80%8A%E8%B4%A3%E4%BB%A4%E9%99%90%E6%9C%9F%E6%95%B4%E6%94%B9%E6%8C%87%E4%BB%A4%E4%B9%A6%E3%80%8B%EF%BC%88%E5%B2%AD%E5%BA%94%E6%80%A5%E8%B4%A3%E6%94%B9%E3%80%942022%E3%80%950017%E5%8F%B7%EF%BC%89%EF%BC%8C%E8%AF%81%E6%98%8E%E4%BD%A0%E5%8D%95%E4%BD%8D1%E3%80%81%E6%9C%AA%E8%90%BD%E5%AE%9E%E5%AE%89%E5%85%A8%E7%94%9F%E4%BA%A7%E8%B4%A3%E4%BB%BB%E5%88%B6%EF%BC%8C%E4%BA%95%E4%B8%8B%E8%B4%9F25%E4%B8%AD%E6%AE%B5%E5%AD%A3%E7%A6%8F%E6%98%9F%EF%BC%88%E6%94%B9%E5%9D%97%E5%B7%A5%EF%BC%89%E3%80%81%E5%88%98%E6%96%B0%E6%B5%B7%EF%BC%88%E9%93%B2%E8%BF%90%E5%8F%B8%E6%9C%BA%EF%BC%89%E3%80%81%E9%87%91%E7%A6%8F%E8%B4%A2%EF%BC%88%E7%A0%B4%E7%A2%8E%E5%8F%B8%E6%9C%BA%EF%BC%89%E6%9C%AA%E9%9A%8F%E8%BA%AB%E6%90%BA%E5%B8%A6%E4%BA%BA%E5%91%98%E5%AE%9A%E4%BD%8D%E5%8D%A1%EF%BC%9B2%E3%80%81%E5%8D%97%E5%8C%BA%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%9F%BF%E9%A2%86%E5%AF%BC%E5%B8%A6%E7%8F%AD%E4%BA%A4%E6%8E%A5%E7%8F%AD%E8%AE%B0%E5%BD%95%E5%BC%84%E8%99%9A%E4%BD%9C%E5%81%87%EF%BC%887%E6%9C%882%E6%97%A5%E7%99%BD%E7%8F%AD%E6%9B%BE%E7%91%9E%E6%99%AF%E5%B8%A6%E7%8F%AD%E4%BA%A4%E6%8E%A5%E7%8F%AD%E8%AE%B0%E5%BD%95%E5%A1%AB%E5%86%99%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B419%EF%BC%9A00%E3%80%81%E4%BA%BA%E5%91%98%E5%AE%9A%E4%BD%8D%E6%98%BE%E7%A4%BA%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B418%EF%BC%9A08%EF%BC%9B7%E6%9C%883%E6%97%A5%E7%99%BD%E7%8F%AD%E5%8D%A2%E7%AB%8B%E5%A6%82%E5%B8%A6%E7%8F%AD%E4%BA%A4%E6%8E%A5%E7%8F%AD%E8%AE%B0%E5%BD%95%E5%A1%AB%E5%86%99%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B419%EF%BC%9A00%E3%80%81%E4%BA%BA%E5%91%98%E5%AE%9A%E4%BD%8D%E6%98%BE%E7%A4%BA%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B415%EF%BC%9A50%EF%BC%9B7%E6%9C%884%E6%97%A5%E7%99%BD%E7%8F%AD%E5%91%A8%E4%B9%89%E5%9D%9A%E5%B8%A6%E7%8F%AD%E4%BA%A4%E6%8E%A5%E7%8F%AD%E8%AE%B0%E5%BD%95%E5%A1%AB%E5%86%99%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B419%EF%BC%9A00%E3%80%81%E4%BA%BA%E5%91%98%E5%AE%9A%E4%BD%8D%E6%98%BE%E7%A4%BA%E5%8D%87%E4%BA%95%E6%97%B6%E9%97%B418%EF%BC%9A09%EF%BC%89%EF%BC%9B3%E3%80%81%E5%8D%

**Comment by baiy** [comment]
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/2341581/181186891-bb0ccd64-98af-4a1e-8b3b-9d16df3777b2.png">
编码不完整导致的解法失败 删除红色框里面的字符即可

**Comment by Asura88** [comment]
建议提供容错支持，大部分软件都是可以支持容错的，比如科来

<img width="652" alt="image" src="https://user-images.githubusercontent.com/25000885/181190469-bc554147-55e4-4424-b957-254c12f8ad8c.png">
