### ISSUE TITLE
增加 db/倍    以及 dbm/dbw/W 的单位转换

### ISSUE THREAD

**Issue by heartacker** [baiy/Ctool#157]
感谢。

**Comment by baiy** [comment]
根据我这边的初步检索网络信息 db和dbm无法相互转换 
https://www.rapidtables.com/electric/dBm.html#dB_to_dBm

这种单位转换涉及专业知识 我不是对应专业的从业人员 @heartacker 如有更多信息可以继续回复这个`issues`提供给我 欢迎pr  `issues`我暂时先关闭了

**Comment by heartacker** [comment]
你好，我的意思不是说想转换 db 和dbm

而是dbm 和dbw 以及 W 之间的转换。

![image](https://user-images.githubusercontent.com/1876302/215312545-f3663a48-d038-4465-90ce-f4c60845c1cb.png)

也就是这个转换吧：

**Comment by heartacker** [comment]
另外这是 db 的 https://www.rapidtables.com/electric/decibel.html
