### ISSUE TITLE
希望在代码格式化后，复制能够保留代码颜色。

### ISSUE THREAD

**Issue by wangzhilin777** [baiy/Ctool#165]
现在格式化后，复制默认是没有颜色的，部分代码想放到笔记软件里面，如果能够支持颜色复制，在查询笔记的时候看着更明了，更快理解代码。望加入复制内容颜色的选项。
辛苦开发者！感谢！

**Comment by chenbowu** [comment]
这个跟复制没有关系，只要你的笔记软件支持代码高亮就可以，将代码内容放到代码块中，软件就会自动高亮。

**Comment by wuyudi** [comment]
可能有关 https://www.ultraedit.com/support/tutorials-power-tips/ultraedit/copy-paste-syntax-highlighting.html

具体我没研究过

**Comment by baiy** [comment]
![image](https://user-images.githubusercontent.com/2341581/217996609-3c286cf7-f5e3-44ae-864c-0be8a385f3bf.png)

![image](https://user-images.githubusercontent.com/2341581/217996741-bfe0071f-a274-4606-bc15-0e78304e61b3.png)

**Comment by wangzhilin777** [comment]
> ![image](https://user-images.githubusercontent.com/2341581/217996609-3c286cf7-f5e3-44ae-864c-0be8a385f3bf.png)
> 
> ![image](https://user-images.githubusercontent.com/2341581/217996741-bfe0071f-a274-4606-bc15-0e78304e61b3.png)

好的，谢谢开发者。
