### ISSUE TITLE
转换时间戳出错

### ISSUE THREAD

**Issue by mofazhe** [baiy/Ctool#167]
似乎是位数限制的问题小于1000000000000毫秒的时间都无法转换
![image](https://user-images.githubusercontent.com/41715438/199025342-d97c148c-46f5-4da7-a83a-ff04484de772.png)
![image](https://user-images.githubusercontent.com/41715438/199025435-678fbbc0-323c-497a-87a0-ccce146d1c30.png)

下图是使用[Unix时间戳(Unix timestamp)转换工具 - 站长工具](https://tool.chinaz.com/tools/unixtime.aspx)转换成功
![image](https://user-images.githubusercontent.com/41715438/199025677-ec8d95a5-b855-43b0-93ab-75c54cb65551.png)

**Comment by baiy** [comment]
新版已修复
