### ISSUE TITLE
unicode 识别功能

### ISSUE THREAD

**Issue by itldg** [baiy/Ctool#186]
复制 `\u6211\u662f\u8001\u5927\u54e5` 后打开 `utools`
![image](https://user-images.githubusercontent.com/13432299/210973341-45b4d3e1-cfb5-408d-bf86-656c64fb4e18.png)

进入 `编码小助手` 即可看到还原后结果
![image](https://user-images.githubusercontent.com/13432299/210973483-14c642e4-a2b2-4d4c-971f-ad14ca939f74.png)

进入`Ctool`后是编码界面

![image](https://user-images.githubusercontent.com/13432299/210973624-534d1dcd-a6eb-4b9c-b48d-2da5958149a3.png)

如果直接解码,效果比较好些

![image](https://user-images.githubusercontent.com/13432299/210973677-f0f9f6a7-044b-4e50-b236-2c864232c788.png)

**Comment by baiy** [comment]
unicode 工具并不会识别输入格式 只会老老实实进行编码或者解码

根据你的输入 在编码页面 因为默认选中了`忽略Ascli编码` 所以看不多编码效果

**Comment by itldg** [comment]
我理解的是
```
 getTool('unicode').getFeature('encoder'),//这里是不是应该是decode之类的
    [
        {
            "type": "regex",
            "match": "/\\\\u[0-9a-f]{4}/i",
            "minLength": 6
        }
    ]
```

正则匹配到unicode代码后进入到了编码界面,理想的应该进入
<img width="314" alt="image" src="https://user-images.githubusercontent.com/13432299/210999958-78243807-c989-457d-988b-e97abaa474a5.png">

**Comment by baiy** [comment]
> 我理解的是
> 
> ```
>  getTool('unicode').getFeature('encoder'),//这里是不是应该是decode之类的
>     [
>         {
>             "type": "regex",
>             "match": "/\\\\u[0-9a-f]{4}/i",
>             "minLength": 6
>         }
>     ]
> ```
> 
> 正则匹配到unicode代码后进入到了编码界面,理想的应该进入 <img alt="image" width="314" src="https://user-images.githubusercontent.com/13432299/210999958-78243807-c989-457d-988b-e97abaa474a5.png">

@itldg 我的锅 我的锅  你的理解是对的 下一版本来修复这个问题

**Comment by itldg** [comment]
我是有心帮你修复的...
代码也拉取下来了, `pnpm` 也安装了,奈何一直卡在
<img width="882" alt="image" src="https://user-images.githubusercontent.com/13432299/211001791-0606b344-c6a9-4178-9b74-f2deb809c24d.png">

少侠,只能靠你了

**Comment by baiy** [comment]
祖国的`墙`阻挡了你 😀
