### ISSUE TITLE
希望增加简单的文本转JSON功能

### ISSUE THREAD

**Issue by qq1623299667** [baiy/Ctool#189]
实际开发中，我经常会用到很多参数，我习惯直接写出来，类似这样
```
user:张三
id:15
age:24
```
我希望可以直接快速转换成JSON，类似这样
```
{
    "user": "张三",
    "id": 15,
    "age": 24
}
```
可以识别出文本，数字类型，并做对应的转换
虽然我可以开发一个工具来做这个事情，但是我已经习惯用这个插件了，我希望这个功能可以直接集成在ctool里面，这样我就不需要多出一个工具去做这个转换，望采纳

**Comment by baiy** [comment]
由于当前版本(v2.0.1)依赖的 [npm:jsonrepair](https://www.npmjs.com/package/jsonrepair) 引用版本较低, 暂时无法实现, 后续升级该依赖后可用下面的方法

将你这种文本前后添加大括号(`{}`) 点击 `JSON 修复`即可

> ps: 可以临时使用在线版本 <https://baiy.github.io/Ctool/>

![image](https://user-images.githubusercontent.com/2341581/211706751-51665be9-a094-4913-aa35-e21a34a41c1a.png)
