### ISSUE TITLE
在chrome环境下用时间相关工具报错

### ISSUE THREAD

**Issue by arron9** [baiy/Ctool#190]
![image](https://user-images.githubusercontent.com/24889276/211703691-deb61844-1189-4d8f-8b43-d9c2bd4d1f88.png)

**Comment by baiy** [comment]
升级一下chrome
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/supportedValuesOf
这个函数是插件用来支持时区切换的
