### ISSUE TITLE
个人使用体验：新界面使用不如之前那么顺畅。我在使用一些功能的时候和之前对比需要多点几下，更喜欢之前的界面，这种界面上的大改动可以先增加新旧切换功能

### ISSUE THREAD

**Issue by jeff11951** [baiy/Ctool#191]

**Comment by Charles94jp** [comment]
+1 
我都是全屏到浏览器标签页使用的，书签里收藏url
现在切换工具十分地不好找，右上角点击一次，再查找，不如之前的直观

**Comment by pconcool** [comment]
新界面太难用，效率太低。建议换回之前UI

**Comment by lwmacct** [comment]
确实难以适应,  每次还得点一下右上角

**Comment by baiy** [comment]
@jeff11951 @pconcool @lwmacct @Charles94jp 
布局优化已经完成 各平台都已经在走发布审核流程了
<https://baiy.github.io/Ctool/>
