### ISSUE TITLE
增加 `Backslash Escape/Unescape` 功能

### ISSUE THREAD

**Issue by bytemain** [baiy/Ctool#204]
在开发中，有些文本复制出来是带 `\n` 的，这个时候想把 `\n` 去掉，有个工具的话就很方便。

### Example

Input:
```
\n\tallow.auto.create.topics = true\n\tauto.commit.interval.ms = 5000\n\tauto.offset.reset = latest\n\tbootstrap.servers = [kafka.service.consul:9092]\n\tcheck.crcs = true\n\tclient.dns.lookup = default\n\t
```

Output:
```
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [kafka.service.consul:9092]
	check.crcs = true
	client.dns.lookup = default
	
```

**Comment by bytemain** [comment]
https://en.wikipedia.org/wiki/Escape_character

JavaScript uses the \ (backslash) as an escape character for:[1][2]

- \' single quote
- \" double quote
- \\ backslash
- \n new line
- \r carriage return
- \t tab
- \b backspace
- \f form feed
- \v vertical tab ([Internet Explorer 9](https://en.wikipedia.org/wiki/Internet_Explorer_9) and older treats '\v as 'v instead of a vertical tab ('\x0B). If cross-browser compatibility is a concern, use \x0B instead of \v.)
- \0 null character (U+0000 NULL) (only if the next character is not a decimal digit; else it is an octal escape sequence)
- \xFF character represented by the hexadecimal byte "FF"

**Comment by bytemain** [comment]
可以用这两个库：
- https://www.npmjs.com/package/char-unescape
- https://www.npmjs.com/package/char-escape

**Comment by baiy** [comment]
@bytemain 收到

> 可以用这两个库：
> 
> * https://www.npmjs.com/package/char-unescape
> * https://www.npmjs.com/package/char-escape

**Comment by bytemain** [comment]
感谢大佬，希望之后可以更新一下 utools 插件带上这个特性
