### ISSUE TITLE
希望可以添加一个JSON转TS的功能

### ISSUE THREAD

**Issue by Jioho** [baiy/Ctool#207]
如题，希望可以输入JSON结构直接输出TS定义

**Comment by Jioho** [comment]
发现已经有了~

**Comment by Jioho** [comment]
![image](https://user-images.githubusercontent.com/28078590/215726468-e5436d8d-7cc4-427a-8237-42b922148003.png)
在 “转换成”这里加一个转换为TS定义的。而不是转换为TS类

**Comment by baiy** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/2341581/215727454-ea708e2d-083c-40fd-8201-f6405b45d023.png">
