### ISSUE TITLE
sql参数填充能优化下吗

### ISSUE THREAD

**Issue by MrZhengI** [baiy/Ctool#215]
sql参数填充每次得复制两次

Preparing: INSERT INTO xxx
com.tension.framework.workflow.engine.dao.WfActToolbarDao.insert 02-13 10:48:53.582 DEBUG [http-nio-8080-exec-4] 20884 - ==> Parameters: 58db8538d40e439cb612ba026b9d66c9(String) xxx,
类似这种的能 直接截取Preparing: 和Parameters: 后的文本然后自动完成转换吗

**Comment by baiy** [comment]
@alvinkwok1 这个你有时间优化吗?

**Comment by alvinkwok1** [comment]
有，我自己用的时候也发现了些问题
