### ISSUE TITLE
二维码-生成功能中，自动读取剪切板内容并没有生效

### ISSUE THREAD

**Issue by az666** [baiy/Ctool#223]
二维码-生成功能中，自动读取剪切板内容并没有生效
这个最早的Ctool版本没有问题的，非常的丝滑，因为我经常使用这个组件，而且我是utools调用其他组件组装链接，然后拷贝到剪切板以后再调用Ctool二维码组件进行生成。但是目前Ctool却无法自动读取剪切板了

**Comment by baiy** [comment]
由于权限和用户隐私问题  默认不在自动读取剪贴板内容  可进入插件配置界面,勾选自动读取剪贴板内容

<img width="619" alt="image" src="https://user-images.githubusercontent.com/2341581/224219866-f718cd5b-e41f-4f3c-bb2f-a4fd7fcaa0d3.png">

**Comment by az666** [comment]
这个我开启过了的，你可以测试一下 即使勾选了这里，剪切板内容依然无法在打开二维码的时候自动填充进来，或者没有自动覆盖掉上次的内容。

**Comment by az666** [comment]
![ctool](https://user-images.githubusercontent.com/32945694/224287324-62a3d2a3-e5bd-481d-854d-d7c864339de9.gif)

**Comment by baiy** [comment]
在现在的操作逻辑中  历史数据(上次操作数据)优先级是高于剪贴板数据的 
在上一版中由于写入历史数据有点bug,造成历史数据为空, 所以每次都会使用剪贴板数据 

后续我这边添加一个数据优先级配置 来实现这个你想要的效果

**Comment by az666** [comment]
好的大佬，可以增加一个配置开关。我相信其他人工作中也会用到这个功能，utools组件之间的联动可以实现自动化生成二维码。
