### ISSUE TITLE
希望添加主动关闭按钮，而不是点击其他地方自动关闭

### ISSUE THREAD

**Issue by imic07** [baiy/Ctool#235]
因为有时候需要从其他地方多次拷贝数据，再次切换过来的时候，这个弹窗就自己关闭了，重新打开之前的数据就没有了，很不方便。
![image](https://user-images.githubusercontent.com/16321067/232278683-3cb5a067-be9c-436a-931c-90bdab35fc7a.png)

**Comment by baiy** [comment]
右上角扩展页面关闭是浏览器控制的  暂时无法设置 可以点击图片中按钮在新页面打开
<img width="737" alt="image" src="https://user-images.githubusercontent.com/2341581/232290439-d56e24dd-9dc1-4a39-a121-daf70301f5a5.png">
