### ISSUE TITLE
希望新增个corn表达式生成器。以及优化下正则表达式

### ISSUE THREAD

**Issue by imic07** [baiy/Ctool#237]
1. corn表达式 参考 https://cron.qqe2.com/
![image](https://user-images.githubusercontent.com/16321067/232311131-1ffb0764-1990-4914-888b-27bc5afafbcb.png)

2. 正则表达式最好增加个常用的正则，开箱即用，能生成对应的程序代码就更好了， 参考： https://tool.lu/regex/
![image](https://user-images.githubusercontent.com/16321067/232311982-9e4bec72-11d2-41d9-bf18-a94c9998ef3f.png)

**Comment by baiy** [comment]
crontab表达式生成已实现 , 正则代码生成暂时还没有想好怎么做, 容我考虑考虑
