### ISSUE TITLE
功能建议 url参数解析

### ISSUE THREAD

**Issue by SvenZhao** [baiy/Ctool#245]
![6a7f1klq](https://user-images.githubusercontent.com/11209750/236752873-eef8da60-5917-4db4-bd45-8501ebcf3872.png)

实现类似这样的界面 能够快速的编辑url的参数

**Comment by baiy** [comment]
这个可以有 欢迎 `PR`

**Comment by SvenZhao** [comment]
@baiy 0 0 刚看了一下 能力有限 代码结构太复杂

**Comment by alvinkwok1** [comment]
没人处理的话我周末空的时候可以提个基本的PR

**Comment by baiy** [comment]
> 没人处理的话我周末空的时候可以提个基本的PR

👍

**Comment by alvinkwok1** [comment]
@SvenZhao 这个能否提供一个具体的样例的地址？其中的hash指哪部分？

**Comment by SvenZhao** [comment]
@alvinkwok1 
![image](https://github.com/baiy/Ctool/assets/11209750/f869f197-9a27-48a4-a22c-ed18c73a0208)
