### ISSUE TITLE
Too high dependency version in Tauri Linux package

### ISSUE THREAD

**Issue by momobobe** [baiy/Ctool#247]
GLibc and OpenSSL of the versions used for build are only available on Ubuntu 22 and Debian 12 or higher, which leads to poor compatibility that earlier systems simply cannot run. Please consider to build with Ubuntu 20.04 instead of Ubuntu latest on Github.

Furthermore, https://tauri.app/v1/guides/building/linux/#limitations and particularly https://github.com/tauri-apps/tauri/issues/1355 discussed about how to decrease dependency versions for more general compatibility

**Comment by baiy** [comment]
I will optimize it later.

**Comment by baiy** [comment]
使用20.04 构建出现有报错, 暂时无法处理, 恢复使用 ubuntu-latest 构建

https://github.com/baiy/Ctool/actions/runs/6207668329/job/16853082993
