### ISSUE TITLE
Support more image formats for QR Code parsing

### ISSUE THREAD

**Issue by momobobe** [baiy/Ctool#248]
It surprised me that QR Code parsing asks for png-only images. Please add support for some other common formats. Thanks.

**Comment by baiy** [comment]
I will optimize it later.

**Comment by baiy** [comment]
The project uses 'qrcode-parser' for QR code parsing, which recently added parsing support for other file formats. Please wait for our project release to include this update.
https://github.com/sinchang/qrcode-parser/pull/22
