### ISSUE TITLE
sql参数填充，有json格式的字符串，会导致填充报错

### ISSUE THREAD

**Issue by imic07** [baiy/Ctool#250]
随便写个insert 语句，插件中使用如下参数，会报错， 在官网使用最新版测试，虽然不报错，但是参数不正确，有丢失：
`
1(Integer), {"goodsService":[],"goodsSpecs":{"id":"db6c56a224a788c5a7458017731c9255","imageFileId":"16925e7fc297452a984d4b3e2e9e6e40"}}(String)
`

**Comment by alvinkwok1** [comment]
问题收到，空了修下，之前用到json的情况比较少，没有考虑这种场景
