### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by PShiYou** [baiy/Ctool#251]
Hello, can you add a page to format headers?
python spiders need to add header information
This headers page has three small functions: formatting headers, formatting cookies, and formatting formdata
As with pycharm's headers plugin, I prefer to use vscode, but vscode doesn't have a similar plugin

**Comment by PShiYou** [comment]
我截图给你看看
![1](https://github.com/baiy/Ctool/assets/118948488/82cea0b2-525a-4781-bca2-76fbf0a5210c)
![2](https://github.com/baiy/Ctool/assets/118948488/a08a05b0-2621-4e70-b1e7-b89743809d7a)
![3](https://github.com/baiy/Ctool/assets/118948488/c401bedf-6454-40cb-84a6-deff3c209fad)
![格式化后的headers](https://github.com/baiy/Ctool/assets/118948488/9fae6ee1-8350-4102-a009-b242a1f31251)
![格式化后的cookies](https://github.com/baiy/Ctool/assets/118948488/95ec149a-ac7c-4647-a1ab-f272b9523d5a)
![格式化formdata](https://github.com/baiy/Ctool/assets/118948488/795ece49-d0b1-45ab-9245-a98036f63802)

**Comment by PShiYou** [comment]
大佬可以做一个吗

**Comment by baiy** [comment]
我看了<https://plugins.jetbrains.com/plugin/18299-headers> 这个插件 我大致了解了你的要求

<https://ctool.dev/tool.html#/tool/httpSnippet> 这个功能应该可以满足你部分需求, 后续我也会在这个功能上优化

ps: 上面这个功能的输入在chrome开发者工具中右键请求-复制为cURL

<img width="640" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/52fbdefd-76aa-4ee6-a476-4e7dc056b46f">

**Comment by baiy** [comment]
<img width="952" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/015a29b3-e8a8-4c0f-a4af-03a27d107e96">

**Comment by PShiYou** [comment]
@baiy 佬，https请求工具有个小bug（python的），网页headers里的某个key的value值带有引号，使用你的开发的工具并未将引号转义。列如：Sec-Ch-Ua:"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"    
![2](https://github.com/baiy/Ctool/assets/118948488/e531bbb7-0f9b-4990-9f2a-9afbdafce2ff)
![1](https://github.com/baiy/Ctool/assets/118948488/abadf867-d967-4134-892c-8758d572184a)
![3](https://github.com/baiy/Ctool/assets/118948488/bc220f41-e157-4c02-9d6d-33b5b008260b)

**Comment by liuxeuman** [comment]
看到有人提了，我就不发了
