### ISSUE TITLE
Json工具压缩后还添加了很多空格，这个可以去掉吗？

### ISSUE THREAD

**Issue by cheshun520** [baiy/Ctool#255]
本来压缩是想去掉多余的格式，结果又添加了很多空格进来，这太多余了

**Comment by caoPhoenix** [comment]
**示例：**
+ 压缩前：
```json
{
    "name": "Gaussian",
    "age": 128
}
```

+ 压缩后：
```json
{"name": "Gaussian","age": 128}
```

注意到：每个 key 的冒号后、value 前都有一个空格。实际上很多JSON工具的压缩不会有这个空格。

**Comment by jan-bar** [comment]
![image](https://github.com/user-attachments/assets/56bb6a83-2d85-4902-a50e-5203c4c46a97)

我加了这段代码可以去除这部分空格: `.replace(/(":\s)/g, '":')`

不过我感觉有更好的方案
