### ISSUE TITLE
json 转义 工具按钮建议直接分拆成两个“添加转义” 和 “移除转义” 直接显示在界面上。

### ISSUE THREAD

**Issue by julyice** [baiy/Ctool#257]
转义的添加删除是json 中经常使用的， 所以建议直接放2个按钮在上面。
![image](https://github.com/baiy/Ctool/assets/8566228/1bee88da-99d4-410e-8744-94e190e11c47)

**Comment by baiy** [comment]
空间有限 暂时不做调整
