### ISSUE TITLE
cron解析对L、W等特殊符号的支持不完善

### ISSUE THREAD

**Issue by 52123333** [baiy/Ctool#265]
无法反解析：0 0 0 L-1 * ?，最近10次执行时间解析失败
![image](https://github.com/baiy/Ctool/assets/10076510/c0b1d99f-6e5b-4df5-a593-a55baad587e4)

**Comment by baiy** [comment]
上游解析库不支持这种写法
表达式解析使用的 https://www.npmjs.com/package/cron-parser
