### ISSUE TITLE
按钮放置的有些不太合理，遮挡了数据

### ISSUE THREAD

**Issue by baiyun001** [baiy/Ctool#266]
自动识别编码这个点击框能不能放到下面嘞？放到这里的话，遮挡了数据，如果能放到边框就更好了
![image](https://github.com/baiy/Ctool/assets/30901842/97b9bf19-6e75-4a47-a2df-ba5f7d80d2e5)

**Comment by baiy** [comment]
<img width="839" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/6619531a-df5d-4b5d-a211-85a89c8d8e44">
点击前面的三角符号 可以折叠选项
