### ISSUE TITLE
打开 Data Time页面报错 Cannot read properties of undefined (reading 'label')

### ISSUE THREAD

**Issue by harryleee** [baiy/Ctool#267]
系统：Windows11
桌面客户端、Chrome、Edge均报错。

**Comment by baiy** [comment]
可以提供更加详细的信息吗 我这边测试了 没有发现date time页面有这种报错

**Comment by harryleee** [comment]
> 可以提供更加详细的信息吗 我这边测试了 没有发现date time页面有这种报错

![image](https://github.com/baiy/Ctool/assets/7631075/d91cd4f5-9934-44af-b299-ac2f8b8332d4)
需要提供哪些信息呢？我不太了解前端调试。
