### ISSUE TITLE
请增加一个可以清除数据的按钮

### ISSUE THREAD

**Issue by 80264666** [baiy/Ctool#272]
因为比如加密的时候 AES的密钥在下次打开的时候，依然存在，能否增加一个按钮，清空所有的记录

**Comment by baiy** [comment]
<img width="1205" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/5dd41f36-921d-4b77-976d-21d7ce14a0d1">
在对应工具页面点击`历史记录`按钮, 进入历史记录页面, 可以看到清空按钮

**Comment by 80264666** [comment]
有一键清除所有的功能的数据吗

**Comment by baiy** [comment]
暂时没有一键清除所有数据的功能   程序的数据是存储在 `localStorage` 中(utools在云数据中)  可以自己手动删除  

历史数据是有效期是一周, 过期后会自动移除的
