### ISSUE TITLE
正则表达式

### ISSUE THREAD

**Issue by sunzhengbo** [baiy/Ctool#273]
^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$

这样的表达式无法校验192.168.1.1

**Comment by baiy** [comment]
<img width="1112" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/fc203df6-b737-415e-a7fd-f59d4042e776">
我这边测试可以使用

**Comment by sunzhengbo** [comment]
谢谢，可以了，可能是表达式的结尾存在换行符才导致的
