### ISSUE TITLE
转换->序列化->Properties files 转换 yaml有问题

### ISSUE THREAD

**Issue by yxm9264** [baiy/Ctool#274]
<img width="1794" alt="iShot_2023-07-17_11 26 07" src="https://github.com/baiy/Ctool/assets/50762364/13f99f2e-26d6-4ec9-b215-b200f277b713">

没有正确的转换成yaml格式，希望可以解决，很实用的功能。谢谢～

**Comment by baiy** [comment]
<img width="795" alt="image" src="https://github.com/baiy/Ctool/assets/2341581/6a4c1185-07e5-4bfc-85fe-e57397a94892">
这个应该是你想要的
