### ISSUE TITLE
base64解码图片导致界面卡死

### ISSUE THREAD

**Issue by QAQQL** [baiy/Ctool#278]
图片base64如下
<script src="https://gist.github.com/QAQQL/665c5664d1177dc1196c58f848b59446.js"></script>

![图片](https://github.com/baiy/Ctool/assets/51136763/55adc1cd-e58f-49f2-86c7-399dbce9b857)
能正常解析,能下载,但右上角关闭不会立刻关闭,需等待一个较长的时间才会退出(分离/嵌入时都这样)(每个设备都能100%复现)
还有,这个图片文件的计时器无需一直滚动
直接按下载按钮点击时间定就行,没必要一直更新

**Comment by baiy** [comment]
Fixed
