### ISSUE TITLE
Minor aesthetical issue - Icons

### ISSUE THREAD

**Issue by baltazartroisville** [baiy/Ctool#279]
Hello,

thank you very much for the great work!

I have only one small, purely aesthetical concern.
The (fav)icons have white borders and corners instead of being transparent, that looks pretty ugly in dark mode.

However, not all icons are the same, some are also almost correct and have very few white pixels left on the edges, in general there is quite a lot of variance.

Here is a list of all used icons and icon folders:

1. https://raw.githubusercontent.com/baiy/Ctool/master/packages/ctool-core/public/favicon.ico
2. https://github.com/baiy/Ctool/tree/025fc1bba10722288c99f5200bbbc5fe98c95b09/packages/ctool-core/public/icon
3. https://github.com/baiy/Ctool/tree/025fc1bba10722288c99f5200bbbc5fe98c95b09/packages/ctool-site/public/icon
4. https://github.com/baiy/Ctool/tree/1d16f4fd15d4e62d056d2da315de9b02c28b7bad/icon
5. https://raw.githubusercontent.com/baiy/Ctool/gh-pages/favicon.ico

Many kind regards!

**Comment by baiy** [comment]
Thank you for the report. We will continue to optimize it in the future
