### ISSUE TITLE
Websocket Protobuf

### ISSUE THREAD

**Issue by howcf** [baiy/Ctool#282]
支持連結websocket時，以protobuf的payload datatype發送信息（現在好像只是支持json方式發送？）

**Comment by baiy** [comment]
当前 `websocket` 使用的是 js 原生的 [Websocket](https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket/WebSocket) 对象  交互消息体是字符串 中间没有做处理 

protobuf 需要提前对消息进行编码和解码(序列化算法), 所以暂时无法支持


https://github.com/baiy/Ctool/blob/025fc1bba10722288c99f5200bbbc5fe98c95b09/packages/ctool-core/src/tools/websocket/Websocket.vue#L109-L149
