### ISSUE TITLE
汉字转便宜为什么没有大写呢？  之前都有的来着 ， 就是只要首字母，然后得是大写

### ISSUE THREAD

**Issue by xylogs** [baiy/Ctool#284]
![image](https://github.com/baiy/Ctool/assets/45510005/5acb0b57-d502-4ccc-9681-885e626aed74)
汉字转便宜为什么没有大写呢？  之前都有的来着

就是只要首字母，然后得是大写

**Comment by xylogs** [comment]
汉字转拼音，打错字了上面

**Comment by baiy** [comment]
这个功能还没有发版 #258

可以临时使用在线版
https://ctool.dev/tool.html#/tool/pinyin
