### ISSUE TITLE
功能建议：计算机数据单位进制转换工具

### ISSUE THREAD

**Issue by sunrishe** [baiy/Ctool#286]
希望作者能增加一个计算机数据单位进制转换工具，主要完成1000进位和1024进位之间各单位的相互转换功能。
1000进位主要单位是PB、TB、GB、MB、KB等；
1024进位主要单位是PiB、TiB、GiB、MiB、KiB等。
题外话：Windows中KB、MB、GB等单位采用的是1024进位，表述有误，实际应为KiB、MiB、GiB，导致大量的人询问在Windows中硬盘为何比实际容量小。Android、Linux、Mac等系统采用了正确的表述方法，数据单位是1000进位。

**Comment by baiy** [comment]
#283
