### ISSUE TITLE
Feature Request:  可以自动保存之前的JSON数据

### ISSUE THREAD

**Issue by liuhao2050** [baiy/Ctool#31]

**Comment by baiy** [comment]
当前插件大部分功能是支持自动将结果保存到剪贴板的
![image](https://user-images.githubusercontent.com/2341581/100439571-ac81e900-30de-11eb-8cbb-d420a642aba1.png)

**Comment by liuhao2050** [comment]
emmm... 我可能没有描述清楚，复制的内容一打开就粘贴进去了，之前的历史数据就被覆盖了，可以存几条历史的数据么

**Comment by baiy** [comment]
新版已增加历史记录功能
