### ISSUE TITLE
能不能加一个生成随机密码的功能

### ISSUE THREAD

**Issue by songning4** [baiy/Ctool#36]
该插件非常强大，用起来也非常方便

能不能加一个生成密码的功能，类似[https://suijimimashengcheng.bmcx.com/]这样的，谢谢

**Comment by baiy** [comment]
这个可以使用 `随机字符生成` 应该可以很好的实现你的要求
![image](https://user-images.githubusercontent.com/2341581/105937313-44c12d80-6090-11eb-83a3-d1685118352f.png)

**Comment by songning4** [comment]
@baiy 您好，感谢回复，“随机字符生成”就非常好了，感谢

**Comment by songning4** [comment]
这个工具太完美了，解决了每次需要处理急事的时候还得百度谷歌搜一下，再打开
