### ISSUE TITLE
使用疑问：小红点

### ISSUE THREAD

**Issue by banjintaohua** [baiy/Ctool#39]
小红点有什么方法可以去除吗，点击了还是存在，对于如果不关注的用户来说，满屏的小红点相当难受

![image](https://user-images.githubusercontent.com/34372649/111585947-0ed03800-87fb-11eb-9d35-ae07153e6dbc.png)

**Comment by baiy** [comment]
红点过期时间是10天 后续版本中我来修改红点的显示机制
