### ISSUE TITLE
utools 相关工具不能通过输入框匹配

### ISSUE THREAD

**Issue by SvenZhao** [baiy/Ctool#42]
例如输入 url URL工具不能直接跳入

**Comment by baiy** [comment]
看效果是可以出现工具选项
![image](https://user-images.githubusercontent.com/2341581/116194358-51265680-a763-11eb-936e-6b4466412309.png)

**Comment by SvenZhao** [comment]
![image](https://user-images.githubusercontent.com/11209750/116194729-d14cbc00-a763-11eb-8648-8c15f77bfd1f.png)
我意思是输入匹配

**Comment by baiy** [comment]
暂时还没有做这个功能  后续添加
