### ISSUE TITLE
无法解析小程序二维码

### ISSUE THREAD

**Issue by fentianzhu** [baiy/Ctool#43]
无法解析小程序二维码

**Comment by baiy** [comment]
可以提供一个小程序的二维码吗?

**Comment by fentianzhu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baiy/Ctool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baiy/Ctool] 无法解析小程序二维码 (#43)





 
可以提供一个小程序的二维码吗?
