### ISSUE TITLE
uTools中使用websocket调试时，切到其他小工具时状态会消失

### ISSUE THREAD

**Issue by DabingLYX** [baiy/Ctool#46]
你好，我不知道websocket工具设计是这样还是BUG。
1、通过websocket调试工具连接成功并成功通信。
2、中途切到其他小工具，例如编码转换、加密解密。
3、再切回websocket调试工具，发现连接断掉，交互内容也清空了。

**Comment by baiy** [comment]
这个问题下一版本来解决 
解决方式是使用utools的分离窗口来实现
