### ISSUE TITLE
希望可以发布一个微软edge商店的版本

### ISSUE THREAD

**Issue by Gardevoir-mega** [baiy/Ctool#49]
希望可以发布一个微软edge商店的版本，国内上不去谷歌商店，然后下载crx不知道为啥总是装不上，都是按照教程的步骤做的，大概是电脑的软件环境出了问题。

然后顺便问一下，可以把插件打包之后扔到服务器上对外使用吗，我现在因为装不上插件，所有是这么用的，如果不妥的话我就把网页撤下来。

**Comment by baiy** [comment]
1. edge商店申请过 不知道什么原因没有通过,在找时间去提交
2. 服务器对外使用没有什么问题 毕竟是开源的

**Comment by baiy** [comment]
本地使用 可以使用utools 这个体验可能会更好

**Comment by Gardevoir-mega** [comment]
这个插件就是从utools上发现的，插件挺好用，不过utools不太符合我的使用习惯，感觉还不如直接用网页打开用着顺手。
