### ISSUE TITLE
是否可以增加一个字符串长度计算

### ISSUE THREAD

**Issue by xiaohuiga** [baiy/Ctool#55]
是否可以增加一个字符串长度计算
虽然是很简单的功能，但是都没有附带这种小功能

**Comment by baiy** [comment]
这个功能可以利用编辑器(大部分编辑器都支持)快速完成 而且也不是特别常用
![image](https://user-images.githubusercontent.com/2341581/127459535-e10799ee-debd-405a-ae81-c1e72e6680a9.png)
