### ISSUE TITLE
【功能建议】Chrome插件的快捷键能不能设置成全局的啊

### ISSUE THREAD

**Issue by lzyjxlx** [baiy/Ctool#56]
Chrome插件的快捷键能不能设置成全局的啊，类似Nimbus 截幕 & 屏幕录像机的录屏快捷键一样，谢谢

**Comment by baiy** [comment]
![image](https://user-images.githubusercontent.com/2341581/129206208-1614f6c2-1902-4f25-aea4-2e0e34e9e764.png)

**Comment by lzyjxlx** [comment]
大佬 EDGE 能不能也支持一下，谢谢

**Comment by baiy** [comment]
> 大佬 EDGE 能不能也支持一下，谢谢

新本在已经edge应用商店提交审核了 等待审核通过即可
