### ISSUE TITLE
数组的格式异常

### ISSUE THREAD

**Issue by declandragon** [baiy/Ctool#6]
想请问数组的格式是哪种？输入下面两种会提示格式不对，谢谢
Array
(
    [0] => Array
        (
            [field_name] => 单行文本
            [cue] => 请输入单行
            [field_type] => text
            [item_name] => 2_7_x1k8q2
            [ifempty] => 1
            [field_type_text] => 单行文本
            [ifempty_text] => 是
        )
)
['a'=>1,'b'=>2]

**Comment by baiy** [comment]
已经修复 0.0.5版本
