### ISSUE TITLE
JSON兼容大写U的问题

### ISSUE THREAD

**Issue by maxfong** [baiy/Ctool#62]
`{"test ":"\U6d4b\U8bd5"}`

Parse error on line 1: {"test ":"\U6d4b\U8bd5"} ---------^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by baiy** [comment]
JSON工具中`格式校验`不会兼容这种问题 , 不过我对`unicode转中文 `做了优化 可以支持这种`unicode`转成`中文`
