### ISSUE TITLE
请问为什么快捷键配置不了了?感谢!

### ISSUE THREAD

**Issue by XuShall** [baiy/Ctool#63]
![image](https://user-images.githubusercontent.com/33885653/130001517-3610bf8d-a88f-4755-bce2-4a16f1472878.png)

独立工具窗口可以,激活该扩展程序那里则是一直灰色

**Comment by XuShall** [comment]
补充..:那里都是灰色...但是目前快捷键配置失效了,别的扩展正常

**Comment by baiy** [comment]
> 补充..:那里都是灰色...但是目前快捷键配置失效了,别的扩展正常

这里是`灰色`是正常的 无法使用我这边正在找原因

**Comment by baiy** [comment]
已修复 设置后重启浏览器
