### ISSUE TITLE
单位换算无法使用

### ISSUE THREAD

**Issue by why2785** [baiy/Ctool#66]
单位换算无法使用。
![image](https://user-images.githubusercontent.com/30384355/131958419-98bd08f0-c46b-4d70-8f9b-598856a9a665.png)

控制台log:
14:06:04.769 tool.db1a35f2.js:1 调整窗口大小
14:06:15.733 chunk-vendors.2059efbe.js:74 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at o (chunk-2d210684.c9e29d9d.js:1)
    at Object.calc (chunk-2d210684.c9e29d9d.js:1)
    at chunk-2d210684.c9e29d9d.js:1
    at Array.forEach (<anonymous>)
    at chunk-2d210684.c9e29d9d.js:1
    at Array.forEach (<anonymous>)
    at s.result (chunk-2d210684.c9e29d9d.js:1)
    at rr.get (chunk-vendors.2059efbe.js:74)
    at rr.evaluate (chunk-vendors.2059efbe.js:74)
at @ chunk-vendors.2059efbe.js:74
it @ chunk-vendors.2059efbe.js:74
nt @ chunk-vendors.2059efbe.js:74
e._render @ chunk-vendors.2059efbe.js:74
r @ chunk-vendors.2059efbe.js:74
rr.get @ chunk-vendors.2059efbe.js:74
rr @ chunk-vendors.2059efbe.js:74
Hn @ chunk-vendors.2059efbe.js:74
xr.$mount @ chunk-vendors.2059efbe.js:74
init @ chunk-vendors.2059efbe.js:74
n @ chunk-vendors.2059efbe.js:74
p @ chunk-vendors.2059efbe.js:74
h @ chunk-vendors.2059efbe.js:74
D @ chunk-vendors.2059efbe.js:74
T @ chunk-vendors.2059efbe.js:74
D @ chunk-vendors.2059efbe.js:74
T @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:74
En.e._update @ chunk-vendors.2059efbe.js:74
r @ chunk-vendors.2059efbe.js:74
rr.get @ chunk-vendors.2059efbe.js:74
rr.run @ chunk-vendors.2059efbe.js:74
Xn @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:74
dt @ chunk-vendors.2059efbe.js:74
Promise.then（异步）
st @ chunk-vendors.2059efbe.js:74
mt @ chunk-vendors.2059efbe.js:74
tr @ chunk-vendors.2059efbe.js:74
rr.update @ chunk-vendors.2059efbe.js:74
me.notify @ chunk-vendors.2059efbe.js:74
set @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
tt.updateRoute @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
$e @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ tool.db1a35f2.js:1
Promise.then（异步）
component @ tool.db1a35f2.js:1
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
Ge @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
p @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
r @ chunk-vendors.2059efbe.js:193
$e @ chunk-vendors.2059efbe.js:193
tt.confirmTransition @ chunk-vendors.2059efbe.js:193
tt.transitionTo @ chunk-vendors.2059efbe.js:193
t.push @ chunk-vendors.2059efbe.js:193
（匿名） @ chunk-vendors.2059efbe.js:193
wt.push @ chunk-vendors.2059efbe.js:193
currentTool @ tool.db1a35f2.js:1
rt @ chunk-vendors.2059efbe.js:74
rr.run @ chunk-vendors.2059efbe.js:74
Xn @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:74
dt @ chunk-vendors.2059efbe.js:74
Promise.then（异步）
st @ chunk-vendors.2059efbe.js:74
mt @ chunk-vendors.2059efbe.js:74
tr @ chunk-vendors.2059efbe.js:74
rr.update @ chunk-vendors.2059efbe.js:74
me.notify @ chunk-vendors.2059efbe.js:74
set @ chunk-vendors.2059efbe.js:74
ir.set @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:333
rt @ chunk-vendors.2059efbe.js:74
Yn.e.$emit @ chunk-vendors.2059efbe.js:74
dispatch @ chunk-vendors.2059efbe.js:308
handleClickItem @ chunk-vendors.2059efbe.js:333
click @ chunk-vendors.2059efbe.js:333
rt @ chunk-vendors.2059efbe.js:74
n @ chunk-vendors.2059efbe.js:74
Qi.a._wrapper @ chunk-vendors.2059efbe.js:74
14:06:27.287 chunk-vendors.2059efbe.js:74 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at o (chunk-2d210684.c9e29d9d.js:1)
    at Object.calc (chunk-2d210684.c9e29d9d.js:1)
    at chunk-2d210684.c9e29d9d.js:1
    at Array.forEach (<anonymous>)
    at chunk-2d210684.c9e29d9d.js:1
    at Array.forEach (<anonymous>)
    at s.result (chunk-2d210684.c9e29d9d.js:1)
    at rr.get (chunk-vendors.2059efbe.js:74)
    at rr.evaluate (chunk-vendors.2059efbe.js:74)
at @ chunk-vendors.2059efbe.js:74
it @ chunk-vendors.2059efbe.js:74
nt @ chunk-vendors.2059efbe.js:74
e._render @ chunk-vendors.2059efbe.js:74
r @ chunk-vendors.2059efbe.js:74
rr.get @ chunk-vendors.2059efbe.js:74
rr @ chunk-vendors.2059efbe.js:74
Hn @ chunk-vendors.2059efbe.js:74
xr.$mount @ chunk-vendors.2059efbe.js:74
init @ chunk-vendors.2059efbe.js:74
n @ chunk-vendors.2059efbe.js:74
p @ chunk-vendors.2059efbe.js:74
h @ chunk-vendors.2059efbe.js:74
D @ chunk-vendors.2059efbe.js:74
T @ chunk-vendors.2059efbe.js:74
D @ chunk-vendors.2059efbe.js:74
T @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:74
En.e._update @ chunk-vendors.2059efbe.js:74
r @ chunk-vendors.2059efbe.js:74
rr.get @ chunk-vendors.2059efbe.js:74
rr.run @ chunk-vendors.2059efbe.js:74
Xn @ chunk-vendors.2059efbe.js:74
（匿名） @ chunk-vendors.2059efbe.js:74
dt @ chunk-vendors.2059efbe.js:74
Promise.then（异步）
st @ chunk-vendors.2059efbe.js:74
mt @ chunk-vendors.2059efbe.js:74
tr @ chunk-vendors.2059efbe.js:74
rr.update @ chunk-vendors.2059efbe.js:74
me.notify @ chunk-vendors.2059efbe.js:74
set @ chunk-vendors.2059efbe.js:74
ir.set @ chunk-vendors.2059efbe.js:74
change @ chunk-vendors.2059efbe.js:333
rt @ chunk-vendors.2059efbe.js:74
n @ chunk-vendors.2059efbe.js:74
Qi.a._wrapper @ chunk-vendors.2059efbe.js:74

**Comment by baiy** [comment]
与 #64 相同原因 由于google插件审核有个页面权限没有通过  我移除了该权限 造成无法使用 下一版本来修复

临时使用地址: <https://baiy.github.io/Ctool/>
