### ISSUE TITLE
最近发现不能用了

### ISSUE THREAD

**Issue by nujiakk** [baiy/Ctool#69]
![image](https://user-images.githubusercontent.com/24282937/133098918-397ab6ab-3cc3-4e2a-8fd4-1dffdfbaec9d.png)
一直用的360急速都正常,
最近发现不能用了
![image](https://user-images.githubusercontent.com/24282937/133099137-5e0d1d40-7d6a-417b-bd90-8651d0212d75.png)
删掉重新装的话  可以用,然后不知道什么时间  图标就又灰了
好像是chrome内核版本问题

**Comment by baiy** [comment]
> 到扩展程序管理界面 把下图的信息贴出来
![image](https://user-images.githubusercontent.com/2341581/133919303-d59f2542-a1fc-4243-96a2-6143123841f1.png)

**Comment by nujiakk** [comment]
并没有错误信息的
![image](https://user-images.githubusercontent.com/24282937/134633874-e4f231cc-d555-424f-bed5-db0a2eeab795.png)

**Comment by nujiakk** [comment]
近期也没有更新过浏览器, 莫名其妙就成这样了   删掉重新装可以,然后没注意的时候图标就变灰了

**Comment by nujiakk** [comment]
当时刚有layui的时候,应该是你在他们论坛发的这个,我一直用的这个,现在不能用,每次转个时间戳要用其他的网站  太麻烦了.
这个要能测试接口请求就更好了

**Comment by baiy** [comment]
当前版本扩展的 manifest_version 升级到了 v3 版本   
v3 版本  chrome内核版本 88 才支持
稍后我会给出一个低版本的安装包

可以尝试一些`utools` 的使用方式 也比较方便

**Comment by nujiakk** [comment]
好的  谢谢
我就是感觉插件功能并没有啥变化,忽然不能用了   有点莫名其妙

**Comment by baiy** [comment]
https://github.com/baiy/Ctool/releases 
最新离线安装包
