### ISSUE TITLE
是否可以提供Firefox的支持

### ISSUE THREAD

**Issue by lslk89** [baiy/Ctool#70]
Firefox用户虽然没有chromium内核浏览器用户多, 但也有些用户, 这么好用的工具, 是否可以考虑提供下支持

做了Firefox插件的兼容检查, 目前.crx文件兼容, 可以尝试上架到Firefox的插件中心
这是兼容检测结果:
https://www.extensiontest.com/test/411b7670-184d-11ec-a711-ab1cad425012

![result](https://user-images.githubusercontent.com/24309796/133879567-d4e8beea-2d6c-49f1-9250-5ef132f14f8a.png)
![steps](https://user-images.githubusercontent.com/24309796/133879569-27eb5c8f-3022-4d12-a129-04742bff3d04.png)
[report.json.txt](https://github.com/baiy/Ctool/files/7189410/report.json.txt)

**Comment by lslk89** [comment]
> Firefox用户虽然没有chromium内核浏览器用户多, 但也有些用户, 这么好用的工具, 是否可以考虑提供下支持
> 
> 做了Firefox插件的兼容检查, 目前.crx文件兼容, 可以尝试上架到Firefox的插件中心
> 这是兼容检测结果:
> https://www.extensiontest.com/test/411b7670-184d-11ec-a711-ab1cad425012
> 
> ![result](https://user-images.githubusercontent.com/24309796/133879567-d4e8beea-2d6c-49f1-9250-5ef132f14f8a.png)
> ![steps](https://user-images.githubusercontent.com/24309796/133879569-27eb5c8f-3022-4d12-a129-04742bff3d04.png)
> [report.json.txt](https://github.com/baiy/Ctool/files/7189410/report.json.txt)

发现有相同的issue, 关闭此issue
[https://github.com/baiy/Ctool/issues/8](url)

**Comment by baiy** [comment]
后续来提供支持

**Comment by baiy** [comment]
<https://addons.mozilla.org/addon/ctool/>
