### ISSUE TITLE
可以提供一个钉住的功能吗

### ISSUE THREAD

**Issue by zhongziqiang** [baiy/Ctool#72]
因为在调试的时候可能会频繁的编码和解码,每次都要手动呼出来,可以提供一个钉住的功能吗,类似于翻译里面的钉住在屏幕最前面
![image](https://user-images.githubusercontent.com/19721708/134790917-46a7a5af-5600-4e3d-9967-5709e7e74a2c.png)

**Comment by baiy** [comment]
这个功能 `utools` 已经提供了
如下图:打开进入使用`分离窗口`  , 就可以在窗口的右上角看见`窗口置顶`功能
![image](https://user-images.githubusercontent.com/2341581/134791378-d34c6ed4-1c38-4824-9431-cf1370dcadf4.png)

ps: 
1. 可以双击工具窗口上方空白处 快速进入`分离窗口`
2. 可以在插件选项中设置 `自动分离窗口`
