### ISSUE TITLE
使用 prettier 增强格式化选项

### ISSUE THREAD

**Issue by asukaminato0721** [baiy/Ctool#75]
prettier 支持很多语言, 比如目前的没有的 TypeScript 格式化

```ts
prettier.format("foo ( );", { parser: "typescript" });
```

https://prettier.io/docs/en/api.html

所有支持的类型在这里 https://prettier.io/docs/en/options.html#parser

目测是更改 baiy/Ctool/src/views/tool/library/formatter.js 这个文件

**Comment by baiy** [comment]
@wuyudi 欢迎提交 Pull requests
