### ISSUE TITLE
插件升级造成chrome关闭异常处理方案

### ISSUE THREAD

**Issue by ZanwingMak** [baiy/Ctool#88]
Chrome: 95.0.4638.69
将chrome分多个窗口(不是标签页)时，关闭某个窗口时，所有窗口都崩溃闪退了。
每个扩展开关试了下，试到Ctool不启用就好了....

**Comment by zhaoshuiruoli** [comment]
遇到了同样的问题，卸载重装chrome也不生效

**Comment by baiy** [comment]
> 遇到了同样的问题，卸载重装chrome也不生效
重装chrome不一定能完整刚更新插件,  ***试试删除插件重新安装插件***
@ZanwingMak z

**Comment by zhaoshuiruoli** [comment]
> > 遇到了同样的问题，卸载重装chrome也不生效
> 
> 重装chrome不一定能完整刚更新插件, _**试试删除插件重新安装插件**_ @ZanwingMak

是的，卸载插件重新安装可以，也是用这种方法发现是插件的问题，之前以为是chrome的问题

**Comment by wlight** [comment]
终于发现了这个问题的解决办法，我都想换浏览器用了

**Comment by codezm** [comment]
我也是测出来是这个插件导致的，才来这里的...

**Comment by zhqqqy** [comment]
我靠，原来是这个插件导致的，卸载重装好了

**Comment by leaveslm** [comment]
Cron 表达式工具有问题，解析结果不对  
Cron 表达式规则如下  
![image](https://user-images.githubusercontent.com/19259484/142981759-be7a9088-2e3f-4888-a959-06060e87dc9f.png)
实际解析如下  
![image](https://user-images.githubusercontent.com/19259484/142981862-293b410d-6c08-46b3-bb23-34070e3be45f.png)

**Comment by Dorae132** [comment]
差点就放弃chrome了
