### ISSUE TITLE
新版本chrome开启插件后，关掉任一窗口，chrome所有窗口全关闭

### ISSUE THREAD

**Issue by BigBroB** [baiy/Ctool#92]
新版本chrome开启插件后，关掉任一窗口，chrome所有窗口全关闭。关闭插件后，正常

**Comment by Luckyyyyyyy** [comment]
我也是,刚刚解决了 插件卸载后重新安装就可以了
https://github.com/baiy/Ctool/issues/88

**Comment by baiy** [comment]
重复问题 查看 https://github.com/baiy/Ctool/issues/88
